server:
  port: 9090

spring:
  application:
    name: msvc-course

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_course?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: postgre
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http//localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/


